### ISSUE TITLE
Run Backend And Frontend Concurrently

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/personal-space#7]
Add a script in ```package.json``` to Run the backend and frontend together from a single terminal when in development stage. This can easily be implemented using the **npm package -> concurrently**.

**Comment by nidhi-bhanushali** [comment]
Would like to set this up also , if you could assign it to me

**Comment by tarunnsingh** [comment]
Great, assigned.

**Comment by nidhi-bhanushali** [comment]
I guess I'll be able to install all the dependencies by just using : npm install ?

**Comment by tarunnsingh** [comment]
Well you need to follow [these steps](https://github.com/tarunnsingh/personal-space#steps-for-running-the-app-locally), to get it working locally.

**Comment by nidhi-bhanushali** [comment]
Sure , thankyou!

**Comment by ampsteric** [comment]
I would love to work on this. assign it to me please if not resolved.

**Comment by nidhi-bhanushali** [comment]
I have resolved the issue and made a pull request . So , @tarunnsingh if you could check that out.
